//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartiesOrganization3
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKINGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKINGS()
        {
            this.MENU = new HashSet<MENU>();
        }
    
        public int ID { get; set; }
        public string DATE_OF_PARTY { get; set; }
        public string PLACES { get; set; }
        public Nullable<int> HALL { get; set; }
        public Nullable<int> TENANT { get; set; }
    
        public virtual HALLS HALLS { get; set; }
        public virtual USERS USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU> MENU { get; set; }
    }
}
