//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartiesOrganization3
{
    using System;
    using System.Collections.Generic;
    
    public partial class HALLS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HALLS()
        {
            this.BOOKINGS = new HashSet<BOOKINGS>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SIZE { get; set; }
        public string PLACES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKINGS> BOOKINGS { get; set; }
    }
}
