//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartiesOrganization3
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENTS
    {
        public int ID { get; set; }
        public Nullable<int> DISH { get; set; }
        public Nullable<int> PRODUCT { get; set; }
        public string WEIGHT { get; set; }
    
        public virtual DISHES DISHES { get; set; }
        public virtual PRODUCTS PRODUCTS { get; set; }
    }
}
