//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartiesOrganization3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDEntities : DbContext
    {
        public BDEntities()
            : base("name=BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOOKINGS> BOOKINGS { get; set; }
        public virtual DbSet<DISHES> DISHES { get; set; }
        public virtual DbSet<HALLS> HALLS { get; set; }
        public virtual DbSet<INGREDIENTS> INGREDIENTS { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<PRODUCTS> PRODUCTS { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
